// src/vue/App.vue
<template>
    <div class="wrapper">
        <h1>Vue</h1>
        <pre v-html="syntaxHighlight($store.getters.all)"></pre>
        <div class="content">
            <div>
                <span>{{ $store.getters.count }}</span>
                <button @click="increment">증가</button>
                <button @click="decrement">감소</button>
            </div>
            <ul>
                <li v-for="(user, index) of $store.getters.users" v-bind:key="index">
                    <span>{{ user }}</span>
                    <button @click="deleteUser(i)">-</button>
                </li>
            </ul>
            <form class="form" @submit.prevent="addUser">
                <input class="input" type="text" v-model="$data.user"/>
                <button type="submit">등록</button>
            </form>
        </div>
    </div>
</template>

<script>
import { syntaxHighlight } from './../utils';

export default {
    data() {
        return {
            user: ''
        }
    },
    created() {
        console.log('루트 뷰', this);
    },
    methods: {
        syntaxHighlight(json) {
            return syntaxHighlight(json)
        },
        increment() {
            this.$store.dispatch('increment');
        },
        decrement() {
            this.$store.dispatch('decrement');
        },
        addUser() {
            this.$store.dispatch('addUser', this.$data.user);
            this.$data.user = '';
        },
        deleteUser(index) {
            this.$store.dispatch('deleteUser', index);
        }
    }
}
</script>

<style>

</style>

// src/angular/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Store, select } from '@ngrx/store';
import { Observable } from 'rxjs';
import { syntaxHighlight } from './../../utils';
import { Increment, Decrement, AddUser, DeleteUser } from './../store/actions';

@Component({
    selector: 'angular-root',
    templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {

    public all$: Observable<any>;
    public user: string = '';

    constructor(
        private store: Store<any>
    ) {
        this.all$ = store.pipe(select('main'));
    }

    ngOnInit() {}

    public increment(): void {
        this.store.dispatch(new Increment());
    }

    public decrement(): void {
        this.store.dispatch(new Decrement());
    }

    public addUser(): void {
        this.store.dispatch(new AddUser(this.user));
        this.user = '';
    }

    public deleteUser(index: number): void {
        this.store.dispatch(new DeleteUser(index));
    }

    public syntaxHighlight(json: any) {
        return syntaxHighlight(json);
    }
}
<div class="wrapper">
    <h1>Angular</h1>
    <!-- {{ all$ | async | json }} -->
    <pre [innerHtml]="syntaxHighlight(all$ | async)"></pre>
    <div class="content">
        <div>
            <span>{{ (all$ | async).count }}</span>
            <button (click)="increment()">증가</button>
            <button (click)="decrement()">감소</button>
        </div>
        <ul>
            <li *ngFor="let user of (all$ | async).users; let i = index">
                <span>{{ user }}</span>
                <button (click)="deleteUser(i)">-</button>
            </li>
        </ul>
        <form class="form" (ngSubmit)="addUser()">
            <input class="input" type="text" [(ngModel)]="user" [ngModelOptions]="{standalone: true}"/>
            <button type="submit">등록</button>
        </form>
    </div>
</div>
